config/routes.rb
Rails.application.routes.draw do
  resources :colour_arts
  root to: 'colour_arts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/colour_art.rb
class ColourArt < ApplicationRecord
end

app/models/colour_piece.rb
class ColourPiece < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colour_arts_controller.rb
class ColourArtsController < ApplicationController
  before_action :set_colour_art, only: [:show, :edit, :update, :destroy]

  # GET /colour_arts
  # GET /colour_arts.json
  def index
    @colour_arts = ColourArt.all
  end

  # GET /colour_arts/1
  # GET /colour_arts/1.json
  def show
  end

  # GET /colour_arts/new
  def new
    @colour_art = ColourArt.new
  end

  # GET /colour_arts/1/edit
  def edit
  end

  # POST /colour_arts
  # POST /colour_arts.json
  def create
    @colour_art = ColourArt.new(colour_art_params)

    respond_to do |format|
      if @colour_art.save
        format.html { redirect_to @colour_art, notice: 'Colour art was successfully created.' }
        format.json { render :show, status: :created, location: @colour_art }
      else
        format.html { render :new }
        format.json { render json: @colour_art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colour_arts/1
  # PATCH/PUT /colour_arts/1.json
  def update
    respond_to do |format|
      if @colour_art.update(colour_art_params)
        format.html { redirect_to @colour_art, notice: 'Colour art was successfully updated.' }
        format.json { render :show, status: :ok, location: @colour_art }
      else
        format.html { render :edit }
        format.json { render json: @colour_art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colour_arts/1
  # DELETE /colour_arts/1.json
  def destroy
    @colour_art.destroy
    respond_to do |format|
      format.html { redirect_to colour_arts_url, notice: 'Colour art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colour_art
      @colour_art = ColourArt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colour_art_params
      params.require(:colour_art).permit(:name, :author, :url, :colorRank, :color, :description)
    end
end

app/controllers/colour_pieces_controller.rb
class ColourPiecesController < ApplicationController
  before_action :set_colour_piece, only: [:show, :edit, :update, :destroy]

  # GET /colour_pieces
  # GET /colour_pieces.json
  def index
    @colour_pieces = ColourPiece.all
  end

  # GET /colour_pieces/1
  # GET /colour_pieces/1.json
  def show
  end

  # GET /colour_pieces/new
  def new
    @colour_piece = ColourPiece.new
  end

  # GET /colour_pieces/1/edit
  def edit
  end

  # POST /colour_pieces
  # POST /colour_pieces.json
  def create
    @colour_piece = ColourPiece.new(colour_piece_params)

    respond_to do |format|
      if @colour_piece.save
        format.html { redirect_to @colour_piece, notice: 'Colour piece was successfully created.' }
        format.json { render :show, status: :created, location: @colour_piece }
      else
        format.html { render :new }
        format.json { render json: @colour_piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colour_pieces/1
  # PATCH/PUT /colour_pieces/1.json
  def update
    respond_to do |format|
      if @colour_piece.update(colour_piece_params)
        format.html { redirect_to @colour_piece, notice: 'Colour piece was successfully updated.' }
        format.json { render :show, status: :ok, location: @colour_piece }
      else
        format.html { render :edit }
        format.json { render json: @colour_piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colour_pieces/1
  # DELETE /colour_pieces/1.json
  def destroy
    @colour_piece.destroy
    respond_to do |format|
      format.html { redirect_to colour_pieces_url, notice: 'Colour piece was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colour_piece
      @colour_piece = ColourPiece.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colour_piece_params
      params.require(:colour_piece).permit(:name, :url, :color, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colour_arts_helper.rb
module ColourArtsHelper
end

app/helpers/colour_pieces_helper.rb
module ColourPiecesHelper
end

app/views/colour_arts/_form.html.erb
<%= form_with(model: colour_art, local: true) do |form| %>
  <% if colour_art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(colour_art.errors.count, "error") %> prohibited this colour_art from being saved:</h2>

      <ul>
      <% colour_art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :colorRank %>
    <%= form.range_field :colorRank, :min=>0, :max=>255, :class=>"" %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/colour_arts/edit.html.erb
<h1>Editing Colour Art</h1>

<%= render 'form', colour_art: @colour_art %>

<%= link_to 'Show', @colour_art %> |
<%= link_to 'Back', colour_arts_path %>

app/views/colour_arts/index.html.erb
<!--
<p id="notice"><%= notice %></p>

<h1>Colour Arts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Url</th>
      <th>Colorrank</th>
      <th>Color</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colour_arts.each do |colour_art| %>
      <tr>
        <td><%= colour_art.name %></td>
        <td><%= colour_art.author %></td>
        <td><%= colour_art.url %></td>
        <td><%= colour_art.colorRank %></td>
        <td><%= colour_art.color %></td>
        <td><%= colour_art.description %></td>
        <td><%= link_to 'Show', colour_art %></td>
        <td><%= link_to 'Edit', edit_colour_art_path(colour_art) %></td>
        <td><%= link_to 'Destroy', colour_art, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Colour Art', new_colour_art_path %>
-->

<h1>Colored Pieces</h1>

<%= link_to 'New Colour Art', new_colour_art_path, :class=>'new' %>


<div id="wheel">

  <% @colour_arts.each do |colour_art| %>
    <%= link_to colour_art, :id=>'img' do %>
      <img src="<%= colour_art.url %>" />
    <% end %>
  <% end %>
  
</div>

<div id="height">
</div>


<script>

var images = document.getElementsByTagName('img')
var nbImage = images.length
var wheel = document.getElementById('wheel')
var deg = 360 / nbImage
var scrollPos = 0;
var y = 0
/*
var h = document.getElementById('height')
var heightPage =  Math.PI * h.offsetWidth
h.style.height = Math.round(heightPage) + 'px'*/

for (let i = 0 ; i < nbImage ; i++ ){
  images[i].style.transform = 'translatey(calc(-200vh + 15vh)) rotate(' + deg*i + 'deg)'
} // calc : (-)moitié height div + moitié height Img

window.addEventListener('scroll', function() {
  var y = window.scrollY /10
  wheel.style.transform = 'rotate(-' + y + 'deg)'
})

</script>

app/views/colour_arts/new.html.erb
<h1>New Colour Art</h1>

<%= render 'form', colour_art: @colour_art %>

<%= link_to 'Back', colour_arts_path %>

app/views/colour_arts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @colour_art.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @colour_art.author %>
</p>

<p>
  <strong>Url:</strong>
  <%= @colour_art.url %><br>
  <img class="showIMage" src="<%= @colour_art.url %>" />
</p>

<p>
  <strong>Color rank:</strong>
  <%= @colour_art.colorRank %> /256
</p>

<p>
  <strong>Color:</strong>
  <%= @colour_art.color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @colour_art.description %>
</p>

<%= link_to 'Edit', edit_colour_art_path(@colour_art) %> |
<%= link_to 'Back', colour_arts_path %> |
<%= link_to 'Destroy', colour_art_path(@colour_art), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/colour_pieces/_form.html.erb
<%= form_with(model: colour_piece, local: true) do |form| %>
  <% if colour_piece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(colour_piece.errors.count, "error") %> prohibited this colour_piece from being saved:</h2>

      <ul>
      <% colour_piece.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/colour_pieces/edit.html.erb
<h1>Editing Colour Piece</h1>

<%= render 'form', colour_piece: @colour_piece %>

<%= link_to 'Show', @colour_piece %> |
<%= link_to 'Back', colour_pieces_path %>

app/views/colour_pieces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colour Pieces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Color</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colour_pieces.each do |colour_piece| %>
      <tr>
        <td><%= colour_piece.name %></td>
        <td><%= colour_piece.url %></td>
        <td><%= colour_piece.color %></td>
        <td><%= colour_piece.description %></td>
        <td><%= link_to 'Show', colour_piece %></td>
        <td><%= link_to 'Edit', edit_colour_piece_path(colour_piece) %></td>
        <td><%= link_to 'Destroy', colour_piece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Colour Piece', new_colour_piece_path %>

app/views/colour_pieces/new.html.erb
<h1>New Colour Piece</h1>

<%= render 'form', colour_piece: @colour_piece %>

<%= link_to 'Back', colour_pieces_path %>

app/views/colour_pieces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @colour_piece.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @colour_piece.url %>
</p>

<p>
  <strong>Color:</strong>
  <%= @colour_piece.color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @colour_piece.description %>
</p>

<%= link_to 'Edit', edit_colour_piece_path(@colour_piece) %> |
<%= link_to 'Back', colour_pieces_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColourMuseum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>